<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/8/7
 * Time: 17:11
 */
namespace common\components;
use yii\base\Behavior;
use yii\helpers\HtmlPurifier;
use yii\web\Controller;
use yii\web\Response;
use yii\base\Component;
class Filter extends Behavior{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


}